### ISSUE TITLE
Feature: User can view a single random anime from a chosen genre

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/anime-watchers#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can generate a random anime from a chosen genre of their choice. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Sometimes people want to watch an anime of lets say a niche genre like horror or slice of life. With Anime Watchers
users don't need to think about the show they want to watch anymore because it'll be chosen for them.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-26 at 5 48 08 PM](https://user-images.githubusercontent.com/82190583/127077471-c2bd9c47-47c1-4bf4-bffe-113d0d4dc8a1.png)
![Screen Shot 2021-07-26 at 5 48 24 PM](https://user-images.githubusercontent.com/82190583/127077487-e21ca94b-1d92-40b4-92bb-afc3b706e732.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create an index.html, styles.css and main.js file
- [x] link the styles.css and main.js with the index.html
- [x] add blush background image
- [x] create the headline "Trying to watch anime but don't know what to watch?"
- [x] create a form with select tag and option elements for each genre
- [x] create a submit button 
- [x] create a footer for mobile view that has the logo and the Anime Watchers title
- [x] make dummy content for the search results to mold how the DOM tree should look. 
- [x] get the data needed for the DOM tree
- [x] create a form data model
- [x] query the DOM for the submit button.
- [x] create the dom tree function.
- [x] ensure the Dom tree created is functioning correctly 
- [x] add the function to shuffle the data
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
