### ISSUE TITLE
Refactor: 

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/anime-watchers#11]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ]  replace all var keywords with const or let
- [ ]  change functions to arrow functions. 
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
