### ISSUE TITLE
ajax project code cleanup

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/anime-watchers#13]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [x] Delete all files that are no longer needed
- [x] change all file and directory names to lower-kebab-case
- [x] all clickable elements that look like buttons should be buttons or links
- [x] form controls should be grouped together in a form element
- [x] remove all commented out code
- [x] change all CSS class names to lower-kebab-case
- [x] remove all unsed css rule-sets and declarations
- [x] remove all commented out code
- [x] remove all alerts()
- [x] remove all debugger; 
- [x] remove all console.logs
- [x] remove all psuedo-code comments
- [x] do not listen for clicks on submit buttons
- [x] remove all commented out code
