### ISSUE TITLE
ajax-project-polish

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/anime-watchers#16]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [ ]  Open the project polish guide for reference
- [ ] find and address all typos in the project's README and source code
- [ ] Give the project a custom name, according to the guide.
- [ ] use the new name everywhere
- [ ] update repository About section
- [ ] use custom favicon
- [ ] remove all unprofessional content and placeholders.
- [ ] add open Graph meta tags for social media sharing.
- [ ] send a message with the link to this project card.
