### ISSUE TITLE
Portfolio Review Notes

### ISSUE THREAD

**Issue by thebearingedge** [mikesayala/anime-watchers#25]
Hi Mike, here are some notes for your `anime-watchers` project. Be sure to re-read the CSS Guide first.

https://lfz-lms.herokuapp.com/code-guides/Learning-Fuze/curriculum/effective-css

- [x] [Fix logo dimensions](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943586204).
- [x] [Fix header thickness](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943586752).
- [x] [Make form control / button fonts larger and consistent](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943587292)
- [x] [Fix select box text color](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943587739)
- [x] [Add a short explanation of how to use the app](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943588147)
- [x] [Make purpose of Genre select control more obvious](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943590276)
- [x] [Add more descriptive wording to buttons](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943591647)
- [x] [Fix button alignment](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943592000)
- [x] [Use more screen space for content in anime description view](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943593044)
- [x] [indicate successful save to the user](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943594548)
- [x] [disallow duplicates in watch list](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943596729)
- [x] [use a clearer delete icon](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943597224)
- [x] [use more screen space for content in the watchlist view](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943598872)
- [x] [make the Anime Watchers navbar item take you to the home page when clicked](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943599813)
- [x] [fix alignment of art/title in watchlist view](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943600514)
- [x] [make sure that button/select line up on mobile](https://github.com/mikesayala/anime-watchers/issues/25#issuecomment-943605012)

**Comment by thebearingedge** [comment]
The dimensions of your logo are kinda weird. You should make it a proper circle. Avoid relative length units except for column widths. This is covered in the effective css guide.

![image](https://user-images.githubusercontent.com/7432943/137370210-89626820-64f9-4589-9b87-590602e61a10.png)

**Comment by thebearingedge** [comment]
Your header thickness changes with the viewport. It should stay one thickness.
![image](https://user-images.githubusercontent.com/7432943/137370433-4b5c4863-9104-404e-b79c-214fa8882cc2.png)

**Comment by thebearingedge** [comment]
These form controls don't have the same font size. 
![image](https://user-images.githubusercontent.com/7432943/137370529-8ede48e6-c913-40f1-b8a8-da6f1864e690.png)

**Comment by thebearingedge** [comment]
Your select box text shouldn't be white, it's relatively hard to read.
![image](https://user-images.githubusercontent.com/7432943/137370625-ef60aed0-af56-46e9-9a72-0bf5455a4f74.png)

**Comment by thebearingedge** [comment]
You should add a short sentence or two explaining what to do. It's not obvious what the user should do.

![image](https://user-images.githubusercontent.com/7432943/137370698-231bb12e-7f41-4b45-93f3-39d20c871a32.png)

**Comment by thebearingedge** [comment]
It would be helpful if this select box had a label or the default said "Choose Genre" instead of just "Genre".

![image](https://user-images.githubusercontent.com/7432943/137371079-ad9539ca-aceb-47b5-be16-8f593d0a3fd9.png)

**Comment by thebearingedge** [comment]
One of these buttons says "save me" and the other says "click me" but it's not clear what "click me" does just by looking at it.
![image](https://user-images.githubusercontent.com/7432943/137371249-204ac06a-2c85-465d-b08d-b25e18f72554.png)

**Comment by thebearingedge** [comment]
These buttons are not properly aligned
![image](https://user-images.githubusercontent.com/7432943/137371354-26fd3164-4f7c-40db-8a62-a38a9158b579.png)

**Comment by thebearingedge** [comment]
This page content is _really_ small. The text and image should be bigger to use more screen real estate.

![image](https://user-images.githubusercontent.com/7432943/137371542-c622618e-0f6e-400c-a775-78195437b0dd.png)

**Comment by thebearingedge** [comment]
it's not clear what is happening when i click this button. it would be good to show some kind of confirmation (maybe an icon appears) when the user successfully saves something

https://user-images.githubusercontent.com/7432943/137371761-1d3e944a-bcb2-4170-b7b1-d710184fefef.mp4

**Comment by thebearingedge** [comment]
It's possible to add the same anime over and over.
![image](https://user-images.githubusercontent.com/7432943/137372127-a5e1122b-c82a-4841-a84b-4dd3e3f899fb.png)

**Comment by thebearingedge** [comment]
It's not obvious that this is how you delete things from your list. I recommend a font awesome icon instead
![image](https://user-images.githubusercontent.com/7432943/137372248-a254b90f-70ec-46f7-b8b6-5de2f304d78e.png)

**Comment by thebearingedge** [comment]
These should be much bigger. on mobile i recommend showing them all in one vertical list. (see `css-responsive-layout` exercise)

![image](https://user-images.githubusercontent.com/7432943/137372514-05e6302f-e38e-4565-ab20-dc9d1656d4a2.png)

**Comment by thebearingedge** [comment]
I thought that "Anime Watchers" would take me back to the home screen, because it has a pointer cursor, but clicking on it doesn't do anything.

![image](https://user-images.githubusercontent.com/7432943/137372693-726a7a05-2aa6-4a36-9022-a96d6472077f.png)

**Comment by thebearingedge** [comment]
this alignment looks random. I recommend absolutely positioning the delete icon in the upper-right corner of the cover art so that your cover art and title can be centered above one another.

![image](https://user-images.githubusercontent.com/7432943/137372740-dc6fcb9b-e1f2-40b7-91e8-640aeff9bc49.png)

**Comment by thebearingedge** [comment]
On mobile, these buttons don't line up
![image](https://user-images.githubusercontent.com/7432943/137373597-1a30991e-0b4b-4622-809f-ba7efec1a6ae.png)
