### ISSUE TITLE
Feature 2 : User can search by rating

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/anime-watchers#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search by rating

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If users want a show that was highly rated they'll use the ratings bar to search for highly rated animes of the genre. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="211" alt="Screen Shot 2021-07-29 at 12 50 21 PM" src="https://user-images.githubusercontent.com/82190583/127556824-4a3d0af6-0ce1-4f5b-993e-5d0fa97d3fbd.png">
<img width="643" alt="Screen Shot 2021-07-29 at 12 50 10 PM" src="https://user-images.githubusercontent.com/82190583/127556826-d11a1724-78fe-4ef8-a177-658e5022d378.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] add ratings bar to html
- [x] access the score data from the api
- [x] include the score data in the function to search the anime.
- [x] ensure its including the correct score.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
