### ISSUE TITLE
Feature: User can view synopsis of the anime

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/anime-watchers#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can get a synopsis of the anime chosen

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A synopsis of the anime will be created dynamically through the DOM and appear on the results screen. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="209" alt="Screen Shot 2021-07-30 at 10 28 20 AM" src="https://user-images.githubusercontent.com/82190583/127690018-bbfcaaad-24a7-4878-b919-ef8682552421.png">
<img width="643" alt="Screen Shot 2021-07-30 at 10 27 58 AM" src="https://user-images.githubusercontent.com/82190583/127690049-885cd4cc-ee83-40dd-980a-6fc5450a53bd.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] access the synopsis data in the xhr results.
- [x] create a p element in the DOM tree function where the synopsis will go. 
- [x] append the newly created element 
- [x] ensure that the paragraph looks good on desktop and mobile version. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
