### ISSUE TITLE
Feature: User can save to a “want to but probably never will watch” list

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/anime-watchers#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If they want to eventually watch a show that is recommended for them the user can save it to a watch list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click a button and save animes they want to watch in a watch list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="624" alt="Screen Shot 2021-07-31 at 12 57 07 PM" src="https://user-images.githubusercontent.com/82190583/127751120-c82dc137-81c2-48ff-8b04-64e199c36e58.png">
<img width="690" alt="Screen Shot 2021-07-31 at 12 57 27 PM" src="https://user-images.githubusercontent.com/82190583/127751128-88cb2445-76c8-439a-b0df-a42e3b9cec74.png">
<img width="691" alt="Screen Shot 2021-07-31 at 12 57 42 PM" src="https://user-images.githubusercontent.com/82190583/127751132-28041311-32c4-410c-ae59-97447a2d09ec.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a save button in the DOM Tree function.
- [x] add an event listener to the save button.
- [x] add another view in the html with dummy content to mimic how the dom tree will be created.
- [x] create the function for the new DOM tree.
- [x] Put the saved entries in the watch list view. 
- [x] save it to local storage so it stays on the watchlist. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
