### ISSUE TITLE
Feature: User can delete the animes they’ve watched. 

### ISSUE THREAD

**Issue by mikesayala** [mikesayala/anime-watchers#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the delete button to delete the anime's they've watched

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Next to the anime will be a trashcan that they can click. A modal will pop up and they can confirm they would like to delete the anime off the list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="537" alt="Screen Shot 2021-08-05 at 10 15 24 AM" src="https://user-images.githubusercontent.com/82190583/128393233-5ca0e31c-53cf-4f35-b6c1-7d012435d9c5.png">
<img width="533" alt="Screen Shot 2021-08-05 at 10 15 35 AM" src="https://user-images.githubusercontent.com/82190583/128393241-312ff62d-3289-49cd-b4b9-6666bb15bc83.png">
<img width="531" alt="Screen Shot 2021-08-05 at 10 15 44 AM" src="https://user-images.githubusercontent.com/82190583/128393244-65f737a2-987a-4e78-afe2-5ef900d51453.png">
<img width="152" alt="Screen Shot 2021-08-05 at 10 16 58 AM" src="https://user-images.githubusercontent.com/82190583/128393246-6c826fbb-5b7f-46f1-9bbf-ce6acaec478d.png">
<img width="151" alt="Screen Shot 2021-08-05 at 10 17 06 AM" src="https://user-images.githubusercontent.com/82190583/128393248-70c6cb16-d8e8-45c3-9ba7-b55db194e238.png">
<img width="148" alt="Screen Shot 2021-08-05 at 10 17 17 AM" src="https://user-images.githubusercontent.com/82190583/128393250-3ed3c892-0425-4eb7-b216-00abfd4fdaaf.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] add trashcan icon to the side of the pictures in the wallpaper. 
- [x] add an eventListener to the icon to bring up the delete button. 
- [x] add a confirmation screen to the page. 
- [x] if user click yes delete it from the page and the local storage.
- [x] if user click no remain on the watch list page. 
- [x] If there are no animes in the list then show "its not like you have any shows to watch"
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
